name: ci-cd-practice

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: "24"

jobs:
  backend-test-build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgres://test:test@localhost:5432/test-db

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_DB
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: checkout-code
        uses: actions/checkout@v4

      - name: Node-setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: npm
          cache-dependency-path: ./package-lock.json

      - name: installing-packages
        run: npm ci

      - name: run-lint
        run: npm run lint

      - name: run-test
        run: npm run test

      - name: build
        run: npm run build
