name: ci-cd-practice

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: "24"

jobs:
  backend-test-build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v4

      - name: Node-setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: npm
          cache-directory-path: ./ci-cd-day2/package-lock.json

      - name: installing-packages
        run: npm ci

      - name: run-lint
        run: npm run lint

      - name: run-test
        run: npm run test

      - name: build
        run: npm run build
